name: 'Build and push Python package'
description: 'Composite action to build and push a Python package to a repository.'

inputs:
  repository:
    description: "Name of the Python repository"
    required: true
    default: pypi
  username:
    description: "Username for the Python repository"
    required: true
    default: __token__
  password:
    description: "Password for the Python repository"
    required: true
  upload:
    description: "Whether or not to upload the package"
    required: true
    default: true
  sdist:
    description: "Whether or not to build the source distribution"
    required: true
    default: true
  wheel:
    description: "Whether or not to build the wheel"
    required: true
    default: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v2
    - run: python -m pip install build twine
      shell: bash
    # See https://github.com/actions/runner/issues/1483
    - run: python -m build --sdist
      shell: bash
      if: ${{ inputs.sdist == 'true' }}
    - run: python -m build --wheel
      shell: bash
      if: ${{ inputs.wheel == 'true' }}
    - run: python -m twine upload --skip-existing dist/*
      shell: bash
      if: ${{ inputs.upload == 'true' }}
      env:
        TWINE_REPOSITORY: ${{ inputs.repository }}
        TWINE_USERNAME: ${{ inputs.username }}
        TWINE_PASSWORD: ${{ inputs.password }}
