name: 'Build and push Python package'
description: 'Composite action to build and push a Python package to a repository.'

inputs:
  repository:
    description: "Name of the Python repository"
    required: true
    default: pypi
  username:
    description: "Username for the Python repository"
    required: true
    default: __token__
  password:
    description: "Password for the Python repository"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v2
    - run: python -m pip install build twine
    - run: python -m build
    - run: python -m twine upload --skip-existing dist/*
      env:
        TWINE_REPOSITORY: ${{ inputs.repository }}
        TWINE_USERNAME: ${{ inputs.username }}
        TWINE_PASSWORD: ${{ inputs.password }}
